#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only)

if echo "$STAGED_FILES" | grep -q "^backend/"; then
  cd backend
  ./gradlew ktlintFormat --no-daemon
  
  git add . 
  cd ..
fi

if echo "$STAGED_FILES" | grep -q "^frontend/"; then
  cd frontend

  echo "$STAGED_FILES" | grep "^frontend/" | cut -c 10- | xargs -r npx prettier --write
  
  git add .
  cd ..
fi